/**
 * ISO 3166-1 alpha-2 country codes with their international dialling codes.
 * Display names come from `Intl.DisplayNames` in the user's language, so no
 * translated list is stored here.
 */
export interface Country {
  code: string;
  dial: string;
}

export const COUNTRIES: Country[] = [
  { code: 'AD', dial: '376' },
  { code: 'AE', dial: '971' },
  { code: 'AF', dial: '93' },
  { code: 'AG', dial: '1268' },
  { code: 'AL', dial: '355' },
  { code: 'AM', dial: '374' },
  { code: 'AO', dial: '244' },
  { code: 'AR', dial: '54' },
  { code: 'AT', dial: '43' },
  { code: 'AU', dial: '61' },
  { code: 'AW', dial: '297' },
  { code: 'AZ', dial: '994' },
  { code: 'BA', dial: '387' },
  { code: 'BB', dial: '1246' },
  { code: 'BD', dial: '880' },
  { code: 'BE', dial: '32' },
  { code: 'BF', dial: '226' },
  { code: 'BG', dial: '359' },
  { code: 'BH', dial: '973' },
  { code: 'BI', dial: '257' },
  { code: 'BJ', dial: '229' },
  { code: 'BN', dial: '673' },
  { code: 'BO', dial: '591' },
  { code: 'BR', dial: '55' },
  { code: 'BS', dial: '1242' },
  { code: 'BT', dial: '975' },
  { code: 'BW', dial: '267' },
  { code: 'BY', dial: '375' },
  { code: 'BZ', dial: '501' },
  { code: 'CA', dial: '1' },
  { code: 'CD', dial: '243' },
  { code: 'CF', dial: '236' },
  { code: 'CG', dial: '242' },
  { code: 'CH', dial: '41' },
  { code: 'CI', dial: '225' },
  { code: 'CL', dial: '56' },
  { code: 'CM', dial: '237' },
  { code: 'CN', dial: '86' },
  { code: 'CO', dial: '57' },
  { code: 'CR', dial: '506' },
  { code: 'CU', dial: '53' },
  { code: 'CV', dial: '238' },
  { code: 'CY', dial: '357' },
  { code: 'CZ', dial: '420' },
  { code: 'DE', dial: '49' },
  { code: 'DJ', dial: '253' },
  { code: 'DK', dial: '45' },
  { code: 'DM', dial: '1767' },
  { code: 'DO', dial: '1809' },
  { code: 'DZ', dial: '213' },
  { code: 'EC', dial: '593' },
  { code: 'EE', dial: '372' },
  { code: 'EG', dial: '20' },
  { code: 'ER', dial: '291' },
  { code: 'ES', dial: '34' },
  { code: 'ET', dial: '251' },
  { code: 'FI', dial: '358' },
  { code: 'FJ', dial: '679' },
  { code: 'FR', dial: '33' },
  { code: 'GA', dial: '241' },
  { code: 'GB', dial: '44' },
  { code: 'GD', dial: '1473' },
  { code: 'GE', dial: '995' },
  { code: 'GH', dial: '233' },
  { code: 'GI', dial: '350' },
  { code: 'GM', dial: '220' },
  { code: 'GN', dial: '224' },
  { code: 'GQ', dial: '240' },
  { code: 'GR', dial: '30' },
  { code: 'GT', dial: '502' },
  { code: 'GW', dial: '245' },
  { code: 'GY', dial: '592' },
  { code: 'HK', dial: '852' },
  { code: 'HN', dial: '504' },
  { code: 'HR', dial: '385' },
  { code: 'HT', dial: '509' },
  { code: 'HU', dial: '36' },
  { code: 'ID', dial: '62' },
  { code: 'IE', dial: '353' },
  { code: 'IL', dial: '972' },
  { code: 'IN', dial: '91' },
  { code: 'IQ', dial: '964' },
  { code: 'IR', dial: '98' },
  { code: 'IS', dial: '354' },
  { code: 'IT', dial: '39' },
  { code: 'JM', dial: '1876' },
  { code: 'JO', dial: '962' },
  { code: 'JP', dial: '81' },
  { code: 'KE', dial: '254' },
  { code: 'KG', dial: '996' },
  { code: 'KH', dial: '855' },
  { code: 'KR', dial: '82' },
  { code: 'KW', dial: '965' },
  { code: 'KZ', dial: '7' },
  { code: 'LA', dial: '856' },
  { code: 'LB', dial: '961' },
  { code: 'LK', dial: '94' },
  { code: 'LR', dial: '231' },
  { code: 'LT', dial: '370' },
  { code: 'LU', dial: '352' },
  { code: 'LV', dial: '371' },
  { code: 'LY', dial: '218' },
  { code: 'MA', dial: '212' },
  { code: 'MC', dial: '377' },
  { code: 'MD', dial: '373' },
  { code: 'ME', dial: '382' },
  { code: 'MG', dial: '261' },
  { code: 'MK', dial: '389' },
  { code: 'ML', dial: '223' },
  { code: 'MM', dial: '95' },
  { code: 'MN', dial: '976' },
  { code: 'MO', dial: '853' },
  { code: 'MT', dial: '356' },
  { code: 'MU', dial: '230' },
  { code: 'MV', dial: '960' },
  { code: 'MW', dial: '265' },
  { code: 'MX', dial: '52' },
  { code: 'MY', dial: '60' },
  { code: 'MZ', dial: '258' },
  { code: 'NA', dial: '264' },
  { code: 'NG', dial: '234' },
  { code: 'NI', dial: '505' },
  { code: 'NL', dial: '31' },
  { code: 'NO', dial: '47' },
  { code: 'NP', dial: '977' },
  { code: 'NZ', dial: '64' },
  { code: 'OM', dial: '968' },
  { code: 'PA', dial: '507' },
  { code: 'PE', dial: '51' },
  { code: 'PG', dial: '675' },
  { code: 'PH', dial: '63' },
  { code: 'PK', dial: '92' },
  { code: 'PL', dial: '48' },
  { code: 'PR', dial: '1787' },
  { code: 'PT', dial: '351' },
  { code: 'PY', dial: '595' },
  { code: 'QA', dial: '974' },
  { code: 'RO', dial: '40' },
  { code: 'RS', dial: '381' },
  { code: 'RU', dial: '7' },
  { code: 'RW', dial: '250' },
  { code: 'SA', dial: '966' },
  { code: 'SC', dial: '248' },
  { code: 'SD', dial: '249' },
  { code: 'SE', dial: '46' },
  { code: 'SG', dial: '65' },
  { code: 'SI', dial: '386' },
  { code: 'SK', dial: '421' },
  { code: 'SL', dial: '232' },
  { code: 'SN', dial: '221' },
  { code: 'SO', dial: '252' },
  { code: 'SR', dial: '597' },
  { code: 'SV', dial: '503' },
  { code: 'SY', dial: '963' },
  { code: 'TG', dial: '228' },
  { code: 'TH', dial: '66' },
  { code: 'TJ', dial: '992' },
  { code: 'TM', dial: '993' },
  { code: 'TN', dial: '216' },
  { code: 'TR', dial: '90' },
  { code: 'TT', dial: '1868' },
  { code: 'TW', dial: '886' },
  { code: 'TZ', dial: '255' },
  { code: 'UA', dial: '380' },
  { code: 'UG', dial: '256' },
  { code: 'US', dial: '1' },
  { code: 'UY', dial: '598' },
  { code: 'UZ', dial: '998' },
  { code: 'VE', dial: '58' },
  { code: 'VN', dial: '84' },
  { code: 'YE', dial: '967' },
  { code: 'ZA', dial: '27' },
  { code: 'ZM', dial: '260' },
  { code: 'ZW', dial: '263' },
];

/** Localised country name, e.g. countryName('BR', 'pt-BR') -> "Brasil". */
export function countryName(code: string, locale: string): string {
  try {
    return new Intl.DisplayNames([locale], { type: 'region' }).of(code) ?? code;
  } catch {
    return code;
  }
}
